services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - APP_BACKEND_URL=${APP_BACKEND_URL}
    ports:
      - "8080:8080"
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
