/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonUI: typeof import('./components/ui/ButtonUI.vue')['default']
    ColorPicker: typeof import('./components/ui/ColorPicker.vue')['default']
    Down: typeof import('./components/icons/plus/down.vue')['default']
    Down_plus: typeof import('./components/icons/plus/down_plus.vue')['default']
    Down_plusplus: typeof import('./components/icons/plus/down_plusplus.vue')['default']
    DropdownMenu: typeof import('./components/ui/DropdownMenu/DropdownMenu.vue')['default']
    DropdownMenuItem: typeof import('./components/ui/DropdownMenu/DropdownMenuItem.vue')['default']
    EditorMain: typeof import('./components/ui/Editor/EditorMain.vue')['default']
    FooterItem: typeof import('./components/FooterItem.vue')['default']
    HeaderEditor: typeof import('./components/ui/Editor/HeaderEditor.vue')['default']
    HeaderItem: typeof import('./components/HeaderItem.vue')['default']
    HighlightsItem: typeof import('./components/HighlightsItem.vue')['default']
    IconBillCheck: typeof import('./components/icons/IconBillCheck.vue')['default']
    IconClose: typeof import('./components/icons/IconClose.vue')['default']
    IconConfiguration: typeof import('./components/icons/IconConfiguration.vue')['default']
    IconGithub: typeof import('./components/icons/IconGithub.vue')['default']
    IconHeart: typeof import('./components/icons/IconHeart.vue')['default']
    IconLoading: typeof import('./components/icons/IconLoading.vue')['default']
    IconLoading2: typeof import('./components/icons/IconLoading2.vue')['default']
    IconMagicStick: typeof import('./components/icons/IconMagicStick.vue')['default']
    IconPalette: typeof import('./components/icons/IconPalette.vue')['default']
    IconProfileEdit: typeof import('./components/icons/IconProfileEdit.vue')['default']
    IconTelegram: typeof import('./components/icons/IconTelegram.vue')['default']
    IconTwitch: typeof import('./components/icons/IconTwitch.vue')['default']
    IconValory: typeof import('./components/icons/IconValory.vue')['default']
    IconValoryBG: typeof import('./components/icons/IconValoryBG.vue')['default']
    InputUI: typeof import('./components/ui/InputUI.vue')['default']
    LanguageSwitcher: typeof import('./components/ui/LanguageSwitcher.vue')['default']
    LogoutIcon: typeof import('./components/icons/LogoutIcon.vue')['default']
    ModalSettingsEditor: typeof import('./components/ui/Editor/Modal/ModalSettingsEditor.vue')['default']
    ModalWindow: typeof import('./components/ui/ModalWindow.vue')['default']
    OverlayItem: typeof import('./components/OverlayItem.vue')['default']
    PreviewEditor: typeof import('./components/ui/Editor/PreviewEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionSettingsEditor: typeof import('./components/ui/Editor/SectionSettingsEditor.vue')['default']
    SettingsIcon: typeof import('./components/icons/SettingsIcon.vue')['default']
    SupportIcon: typeof import('./components/icons/SupportIcon.vue')['default']
    Switch: typeof import('./components/ui/Switch.vue')['default']
    Up: typeof import('./components/icons/plus/up.vue')['default']
    Up_plus: typeof import('./components/icons/plus/up_plus.vue')['default']
    Up_plusplus: typeof import('./components/icons/plus/up_plusplus.vue')['default']
    UserAccount: typeof import('./components/ui/UserAccount.vue')['default']
  }
}
